// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/receive/pubsub.proto

package receive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Messages      []*PubsubMessage       `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_internal_receive_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_receive_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_internal_receive_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetMessages() []*PubsubMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PubsubMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PublishTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubsubMessage) Reset() {
	*x = PubsubMessage{}
	mi := &file_internal_receive_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubsubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubsubMessage) ProtoMessage() {}

func (x *PubsubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_receive_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubsubMessage.ProtoReflect.Descriptor instead.
func (*PubsubMessage) Descriptor() ([]byte, []int) {
	return file_internal_receive_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *PubsubMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *PubsubMessage) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *PubsubMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PubsubMessage) GetPublishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishTime
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []string               `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_internal_receive_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_receive_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_internal_receive_pubsub_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

var File_internal_receive_pubsub_proto protoreflect.FileDescriptor

const file_internal_receive_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/receive/pubsub.proto\x12\x10google.pubsub.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12;\n" +
	"\bmessages\x18\x02 \x03(\v2\x1f.google.pubsub.v1.PubsubMessageR\bmessages\"\x91\x02\n" +
	"\rPubsubMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12O\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2/.google.pubsub.v1.PubsubMessage.AttributesEntryR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12=\n" +
	"\fpublish_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishTime\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x0fPublishResponse\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\tR\n" +
	"messageIds2[\n" +
	"\tPublisher\x12N\n" +
	"\aPublish\x12 .google.pubsub.v1.PublishRequest\x1a!.google.pubsub.v1.PublishResponseB\x13Z\x11./receive;receiveb\x06proto3"

var (
	file_internal_receive_pubsub_proto_rawDescOnce sync.Once
	file_internal_receive_pubsub_proto_rawDescData []byte
)

func file_internal_receive_pubsub_proto_rawDescGZIP() []byte {
	file_internal_receive_pubsub_proto_rawDescOnce.Do(func() {
		file_internal_receive_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_receive_pubsub_proto_rawDesc), len(file_internal_receive_pubsub_proto_rawDesc)))
	})
	return file_internal_receive_pubsub_proto_rawDescData
}

var file_internal_receive_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_receive_pubsub_proto_goTypes = []any{
	(*PublishRequest)(nil),        // 0: google.pubsub.v1.PublishRequest
	(*PubsubMessage)(nil),         // 1: google.pubsub.v1.PubsubMessage
	(*PublishResponse)(nil),       // 2: google.pubsub.v1.PublishResponse
	nil,                           // 3: google.pubsub.v1.PubsubMessage.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_internal_receive_pubsub_proto_depIdxs = []int32{
	1, // 0: google.pubsub.v1.PublishRequest.messages:type_name -> google.pubsub.v1.PubsubMessage
	3, // 1: google.pubsub.v1.PubsubMessage.attributes:type_name -> google.pubsub.v1.PubsubMessage.AttributesEntry
	4, // 2: google.pubsub.v1.PubsubMessage.publish_time:type_name -> google.protobuf.Timestamp
	0, // 3: google.pubsub.v1.Publisher.Publish:input_type -> google.pubsub.v1.PublishRequest
	2, // 4: google.pubsub.v1.Publisher.Publish:output_type -> google.pubsub.v1.PublishResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_receive_pubsub_proto_init() }
func file_internal_receive_pubsub_proto_init() {
	if File_internal_receive_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_receive_pubsub_proto_rawDesc), len(file_internal_receive_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_receive_pubsub_proto_goTypes,
		DependencyIndexes: file_internal_receive_pubsub_proto_depIdxs,
		MessageInfos:      file_internal_receive_pubsub_proto_msgTypes,
	}.Build()
	File_internal_receive_pubsub_proto = out.File
	file_internal_receive_pubsub_proto_goTypes = nil
	file_internal_receive_pubsub_proto_depIdxs = nil
}
